language: python
python:
  - "3.9"

jobs:
  include:
    - stage: pypi release
      python: "3.9"
      script: echo "Deploying to pypi ..."
      deploy:
        provider: pypi
        username: "__token__"
        password: $PYPI_TOKEN
        on:
          tags: true
